### ISSUE TITLE
Crypto Tech Night

### ISSUE THREAD

**Issue by Stamp9** [PrimitivesLane/Lanes-Choice-Calendar#1]
Event: Crypto Tech Night
Organizer: [@CryptoTechNight](https://space.bilibili.com/1560365248)
Link: https://calendar.google.com/calendar/u/0/embed?src=c_i9stvjsrjkedtls1me2v3dea8k@group.calendar.google.com&ctz=Asia/Hong_Kong
Tags: #blockchain #technology #crypto 
Language: Chinese

**Comment by freeyao** [comment]
Good event to help average people on board which has been held 11 times.
Added.
